security:
  oauth2:
    client:
      clientId: 888139963687-j5tepaq7mdq490qm90t26cknqtmm6pt6.apps.googleusercontent.com
      clientSecret: 7_FLErDkAfAa5rFXhWhaYolo
      accessTokenUri: https://oauth2.googleapis.com/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false